import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import "dotenv/config"
import openapi, { astToString } from "openapi-typescript"
import openapiTS from "openapi-typescript"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const OUTPUT_PATH = path.resolve(__dirname, "../src/types/chatterbox-api.d.ts")

async function main() {
    const apiURL = process.env.CHATTERBOX_API_URL!

    if (!apiURL) {
        console.error("Error: CHATTERBOX_API_URL environment variable not set")
        process.exit(1)
    }

    const openAPIurl = `${apiURL}/openapi.json`
    const ast = await openapiTS(new URL(openAPIurl))
    const contents = astToString(ast)

    const outputDir = path.dirname(OUTPUT_PATH)
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true })
    }

    const header = `/**
    * This file is auto-generated by scripts/sync-api.ts
    * Do not edit manually. Run \`npm run sync-api\` to regenerate.
    * 
    * Generated from ${openAPIurl}
    * Generated at: ${new Date().toISOString()}
    * 
    */
    `

    fs.writeFileSync(OUTPUT_PATH, header + contents)
    console.log(`Types written to: ${OUTPUT_PATH}`)

}

main().catch((err) => {
    console.error("Failed to sync API types: ", err)
    process.exit(1)
})